version: '3'
services:
  yyds:
    container_name: yyds
    image: docker.io/sixuewang/fe:accb164-20210512-1845
    ports:
      - 17000:80
      - 17007:443
    environment:
      - OPEN_API=11.0.0.118
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
